server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "9n7IunqqKMwHgX2ANCN87SYAwEX9B4tROoKjeEbk58eN/XU1G9pLEt0HUJCwjZM6"